navigation:
  navbars:
    main:
      tools:
        helper:
          url: '#'
          icon: fa fa-question-circle
          attrs:
            id: helpButton
            title: "Open help"
          roles: ['ROLE_USER']
        intro:
          url: '#'
          icon: fas fa-desktop
          attrs:
            id: introButton
          roles: ['ROLE_USER']