services:
    _defaults:
        autowire: true
        autoconfigure: true
    # Chargement des services
    ICS\UserhelpBundle\Controller\:
        resource: "../src/Controller"
        tags: ['controller.services_arguments']
    ICS\UserhelpBundle\Service\:
        resource: "../src/Service"
        tags: ['controller.services_arguments']
    ICS\UserhelpBundle\Command\:
        resource: "../src/Command"
        tags: ['controller.services_arguments']
    ICS\UserhelpBundle\Twig\:
        resource: "../src/Twig"
        tags: ['controller.services_arguments']
    ICS\UserhelpBundle\Form\:
        resource: "../src/Form"
        tags: ['controller.services_arguments']
